dist: xenial
language: ruby
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - jruby-9.1.17.0
  - jruby-head
  - ruby-head
jdk:
  - openjdk8 # for jruby
matrix:
  include:
    - rvm: rbx-4
      dist: trusty
      name: Rubinius
  allow_failures:
    - name: Rubinius
    - rvm: ruby-head
addons:
  apt:
    packages:
    - libpcre3
    - libpcre3-dev
env:
  global:
  - JRUBY_OPTS='--debug'
before_install: rvm list
notifications:
  irc: "irc.freenode.org#adhearsion"
