---
steps:
  - label: ":ruby: :rspec: ruby-2-6"
    timeout_in_minutes: 10
    agents:
      queue: ruby-2-6
    command:
      - apt-get install -y libpcre3 libpcre3-dev
      - bundle install
      - bundle exec rake
    artifact_paths:
      - spec/reports/**/*
  - label: ":ruby: :rspec: ruby-2-7" # what web currently uses
    timeout_in_minutes: 10
    agents:
      queue: ruby-2-7
    command:
      - apt-get install -y libpcre3 libpcre3-dev
      - bundle install
      - bundle exec rake
    artifact_paths:
      - spec/reports/**/*
  - label: ":ruby: :rspec: jruby-9-2-7-0" # what apptastic currently uses
    timeout_in_minutes: 10
    agents:
      queue: jruby-9-2-7-0
    command:
      - apt-get install -y libpcre3 libpcre3-dev
      - bundle install
      - bundle exec rake --trace
    artifact_paths:
      - spec/reports/**/*
