---
steps
- label: ":ruby: :rspec:"
  timeout_in_minutes: 10
  matrix:
    ruby-version:
      - 2.4
      - 2.5
      - 2.6
      - 2.7
      - jruby-9.1.17.0
      # - jruby-9.2.7.0 # what apptastic currently uses
      - jruby-9.2.9.0 # close to what apptastic uses
      - jruby-head
  agents:
    queue: "{{matrix.ruby-version}}"
  command:
    - apt-get install -y libpcre3 libpcre3-dev
    - bundle install
  artifact_paths:
    - spec/reports/**/*
