---
steps:
- label: ":ruby: :rspec: ruby-2-4"
  timeout_in_minutes: 10
  agents:
    queue: ruby-2-4
  command:
    - apt-get install -y libpcre3 libpcre3-dev
    - bundle install
    - bundle exec rake
  artifact_paths:
    - spec/reports/**/*
