name: Pipeline
on:
  push:
    branches:
    - "*"
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - 2.4
        - 2.5
        - 2.6
        - 2.7
        - jruby-9.1.17.0
        - jruby-9.2.7.0
        - jruby-head
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y libpcre3 libpcre3-dev
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle exec rake

